#!/bin/bash
# Job name:
#SBATCH --job-name=test
#
# Account:
#SBATCH --account=fc_nonsta
#
# Partition:
#SBATCH --partition=savio2
#
# Quality of Service:
#SBATCH --qos=savio_normal
#
# Wall clock limit:
#SBATCH --time=50:00:30

#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=yufeng_zheng@berkeley.edu
#
## Command(s) to run:
# echo "hello world"
# conda init bash
# conda activate py3
python -u RunRouteT_1 1 10 > result/T_1_1_N_exper_10.txt